version: '3'
services:
  new-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: new-api
    restart: always
    network_mode: host
    ports:
      - "3001:3000"
    environment:
      - TZ=Asia/Shanghai
      - REDIS_CONN_STRING=redis://default:123@localhost:6379
      - SQL_DSN=oneapi:123@tcp(localhost:3306)/oneapi
      - SYNC_FREQUENCY=60
      - CHANNEL_TEST_FREQUENCY=1440
      - GLOBAL_API_RATE_LIMIT=180
      - GLOBAL_WEB_RATE_LIMIT=60
    volumes:
      - /data/one-api1:/data
